### ISSUE TITLE
No Module Named Alex

### ISSUE THREAD

**Issue by QuantumArjun** [cocacola-lab/MineLand#11]
Hi! I'm trying to test Alex in doing one of the sample tasks. I have the simulator running (and am passing the simulator check).

I'm trying to run the sample scripts under the Alex folder. 

However, in this, the agent doesn't appear to be moving (their position vector stays the same). Is there something else I need to do to get Alex to act in the world? 

Upon closer look at the code, I'm getting this error when I try to run any of the scripts in this folder:

'''
Traceback (most recent call last):
  File "/Users/x/Code/multi_agent/MineLand/scripts/alex/test.py", line 94, in <module>
    main()
  File "/Users/x/Code/multi_agent/MineLand/scripts/alex/test.py", line 75, in main
    action = alex.run(obs[0], code_info[0], done, task_info, verbose=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/x/Code/multi_agent/MineLand/mineland/alex/alex_agent.py", line 142, in run
    self.perceive(obs, plan_is_success, critic_info, code_info, vision = True, verbose=verbose)
  File "/Users/x/Code/multi_agent/MineLand/mineland/alex/alex_agent.py", line 59, in perceive
    self.memory_library.perceive(obs, plan_is_success, critic_info, code_info, vision=vision, verbose=verbose)
  File "/Users/x/Code/multi_agent/MineLand/mineland/alex/brain/memory_library.py", line 135, in perceive
    self.add_env(tick, day, time, obs, vision=vision)
  File "/Users/x/Code/multi_agent/MineLand/mineland/alex/brain/memory_library.py", line 266, in add_env
    view_summary = self.viewer.summary(obs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/x/Code/multi_agent/MineLand/mineland/alex/brain/viewer.py", line 48, in summary
    system_message = self.render_system_message()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/x/Code/multi_agent/MineLand/mineland/alex/brain/viewer.py", line 24, in render_system_message
    prompt = load_prompt("vision_summary")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/x/Code/multi_agent/MineLand/mineland/alex/prompt_template/__init__.py", line 4, in load_prompt
    package_path = pkg_resources.resource_filename("alex", "")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/x/miniconda3/envs/mineland/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1181, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/x/miniconda3/envs/mineland/lib/python3.11/site-packages/pkg_resources/__init__.py", line 388, in get_provider
    __import__(moduleOrReq)
ModuleNotFoundError: No module named 'Alex'
''''

How might I address this?

**Comment by YXHXianYu** [comment]
Thanks for trying MineLand.

### Previous quesion: Why isn't the agent in the minimum example moving?

MineLand Simulator and Alex are two distinct components of our project.
MineLand Simulator is a set of APIs and an environment similar to [Gymnasium](https://github.com/Farama-Foundation/Gymnasium), while Alex is a VLM agent built on MineLand

If you only instantiated MineLand, it is expected that the agent doesn't appear to be moving. (Note that `actions = mineland.Action.no_op(AGENT_COUNT)` , where `no_op`  stands for `no operations`)

To see the agent in action, you can write high-level action by yourself or call low-level action space. Also, you can instantiate Alex using `mineland.Alex(.....)` and get actions from the Alex Instance.

### How to instantiate Alex?

**The codebase you using is outdated.**
Please run `git pull` to update to the latest codebase. (You may need to run `git add` and `git commit` to save your local changes first.)
In the latest codebase, we provide **more example** of MineLand.

Currently, we **do not** have an example of the Alex Agent in the latest codebase.
We'll provide an example of Alex **later today**. 😄

**Comment by YXHXianYu** [comment]
[Alex Example](https://github.com/cocacola-lab/MineLand/blob/main/scripts/alex_example.py)

**Comment by QuantumArjun** [comment]
Awesome, thank you so much!
