### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'version')

### ISSUE THREAD

**Issue by WPH22** [cocacola-lab/MineLand#26]
Hello,

When I try to proceed to:

1.7 Validate
# move back to MineLand root directory
cd ../../../
python ./scripts/validate_install_simulator.py

I get the error:

[Mineflayer] TypeError: Cannot read properties of null (reading 'version')
[Mineflayer] at next (/home/wph/MineLand/mineland/sim/mineflayer/node_modules/mineflayer/lib/loader.js:108:67)
[Mineflayer] at Object.createBot (/home/wph/MineLand/mineland/sim/mineflayer/node_modules/mineflayer/lib/loader.js:105:34)
[Mineflayer] at BotManager.createBot (/home/wph/MineLand/mineland/sim/mineflayer/bot_manager.js:55:28)
[Mineflayer] at /home/wph/MineLand/mineland/sim/mineflayer/index.js:39:21

How can I solve this problem?

![Screenshot from 2024-10-13 17-08-30](https://github.com/user-attachments/assets/4241b2c6-817a-42c5-a520-55f6335919ad)

**Comment by YXHXianYu** [comment]
Maybe the dependencies of node.js (mineflayer side) version is not correct.

Execute `npm list` and check the output.

My output of `npm list`' is:

```
# pnpm list
dependencies:
abort-controller 3.0.0                 mineflayer-collectblock-colalab 1.0.0
body-parser 1.20.2                     mineflayer-pathfinder 2.4.5
canvas 2.11.2                          mineflayer-pvp 1.3.2
express 4.19.2                         mineflayer-tool 1.2.0
minecraft-data 3.50.0                  prismarine-viewer-colalab 1.0.11
minecrafthawkeye 1.3.6                 vec3 0.1.8
mineflayer 4.14.0

# npm list
mineflayer@ E:\Data\BJTU\BJTU6\3.ColaLab\Codes\MineLand\mineland\sim\mineflayer
+-- abort-controller@3.0.0 -> .\node_modules\.pnpm\abort-controller@3.0.0\node_modules\abort-controller
+-- body-parser@1.20.2 -> .\node_modules\.pnpm\body-parser@1.20.2\node_modules\body-parser
+-- canvas@2.11.2 -> .\node_modules\.pnpm\canvas@2.11.2_encoding@0.1.13\node_modules\canvas
+-- express@4.19.2 -> .\node_modules\.pnpm\express@4.19.2\node_modules\express
+-- minecraft-data@3.50.0 -> .\node_modules\.pnpm\minecraft-data@3.50.0\node_modules\minecraft-data
+-- minecrafthawkeye@1.3.6 -> .\node_modules\.pnpm\minecrafthawkeye@1.3.6\node_modules\minecrafthawkeye
+-- mineflayer-collectblock-colalab@1.0.0 -> .\node_modules\.pnpm\mineflayer-collectblock-colalab@1.0.0_encoding@0.1.13\node_modules\mineflayer-collectblock-colalab
+-- mineflayer-pathfinder@2.4.5 -> .\node_modules\.pnpm\mineflayer-pathfinder@2.4.5\node_modules\mineflayer-pathfinder
+-- mineflayer-pvp@1.3.2 -> .\node_modules\.pnpm\mineflayer-pvp@1.3.2_encoding@0.1.13_prismarine-registry@1.7.0\node_modules\mineflayer-pvp
+-- mineflayer-tool@1.2.0 -> .\node_modules\.pnpm\mineflayer-tool@1.2.0_encoding@0.1.13\node_modules\mineflayer-tool
+-- mineflayer@4.14.0 -> .\node_modules\.pnpm\mineflayer@4.14.0_encoding@0.1.13\node_modules\mineflayer
+-- prismarine-viewer-colalab@1.0.11 -> .\node_modules\.pnpm\prismarine-viewer-colalab@1.0.11_encoding@0.1.13\node_modules\prismarine-viewer-colalab
`-- vec3@0.1.8 -> .\node_modules\.pnpm\vec3@0.1.8\node_modules\vec3
```

If you found the version is not match. You can check the [package-lock.json](https://github.com/cocacola-lab/MineLand/blob/main/mineland/sim/mineflayer/package-lock.json) under `mineflayer` folder and use `npm ci` to install in correct version.

**Comment by WPH22** [comment]
> 可能是node.js（mineflayer端）的依赖版本不正确。
> 
> 执行`npm list`并检查输出。
> 
> 我的输出`npm list`是：
> 
> ```
> # pnpm list
> dependencies:
> abort-controller 3.0.0                 mineflayer-collectblock-colalab 1.0.0
> body-parser 1.20.2                     mineflayer-pathfinder 2.4.5
> canvas 2.11.2                          mineflayer-pvp 1.3.2
> express 4.19.2                         mineflayer-tool 1.2.0
> minecraft-data 3.50.0                  prismarine-viewer-colalab 1.0.11
> minecrafthawkeye 1.3.6                 vec3 0.1.8
> mineflayer 4.14.0
> 
> # npm list
> mineflayer@ E:\Data\BJTU\BJTU6\3.ColaLab\Codes\MineLand\mineland\sim\mineflayer
> +-- abort-controller@3.0.0 -> .\node_modules\.pnpm\abort-controller@3.0.0\node_modules\abort-controller
> +-- body-parser@1.20.2 -> .\node_modules\.pnpm\body-parser@1.20.2\node_modules\body-parser
> +-- canvas@2.11.2 -> .\node_modules\.pnpm\canvas@2.11.2_encoding@0.1.13\node_modules\canvas
> +-- express@4.19.2 -> .\node_modules\.pnpm\express@4.19.2\node_modules\express
> +-- minecraft-data@3.50.0 -> .\node_modules\.pnpm\minecraft-data@3.50.0\node_modules\minecraft-data
> +-- minecrafthawkeye@1.3.6 -> .\node_modules\.pnpm\minecrafthawkeye@1.3.6\node_modules\minecrafthawkeye
> +-- mineflayer-collectblock-colalab@1.0.0 -> .\node_modules\.pnpm\mineflayer-collectblock-colalab@1.0.0_encoding@0.1.13\node_modules\mineflayer-collectblock-colalab
> +-- mineflayer-pathfinder@2.4.5 -> .\node_modules\.pnpm\mineflayer-pathfinder@2.4.5\node_modules\mineflayer-pathfinder
> +-- mineflayer-pvp@1.3.2 -> .\node_modules\.pnpm\mineflayer-pvp@1.3.2_encoding@0.1.13_prismarine-registry@1.7.0\node_modules\mineflayer-pvp
> +-- mineflayer-tool@1.2.0 -> .\node_modules\.pnpm\mineflayer-tool@1.2.0_encoding@0.1.13\node_modules\mineflayer-tool
> +-- mineflayer@4.14.0 -> .\node_modules\.pnpm\mineflayer@4.14.0_encoding@0.1.13\node_modules\mineflayer
> +-- prismarine-viewer-colalab@1.0.11 -> .\node_modules\.pnpm\prismarine-viewer-colalab@1.0.11_encoding@0.1.13\node_modules\prismarine-viewer-colalab
> `-- vec3@0.1.8 -> .\node_modules\.pnpm\vec3@0.1.8\node_modules\vec3
> ```
> 
> 如果发现版本不匹配，您可以检查文件夹下的[package-lock.json](https://github.com/cocacola-lab/MineLand/blob/main/mineland/sim/mineflayer/package-lock.json)`mineflayer`并使用`npm ci`正确的版本进行安装。



> Maybe the dependencies of node.js (mineflayer side) version is not correct.
> 
> Execute `npm list` and check the output.
> 
> My output of `npm list`' is:
> 
> ```
> # pnpm list
> dependencies:
> abort-controller 3.0.0                 mineflayer-collectblock-colalab 1.0.0
> body-parser 1.20.2                     mineflayer-pathfinder 2.4.5
> canvas 2.11.2                          mineflayer-pvp 1.3.2
> express 4.19.2                         mineflayer-tool 1.2.0
> minecraft-data 3.50.0                  prismarine-viewer-colalab 1.0.11
> minecrafthawkeye 1.3.6                 vec3 0.1.8
> mineflayer 4.14.0
> 
> # npm list
> mineflayer@ E:\Data\BJTU\BJTU6\3.ColaLab\Codes\MineLand\mineland\sim\mineflayer
> +-- abort-controller@3.0.0 -> .\node_modules\.pnpm\abort-controller@3.0.0\node_modules\abort-controller
> +-- body-parser@1.20.2 -> .\node_modules\.pnpm\body-parser@1.20.2\node_modules\body-parser
> +-- canvas@2.11.2 -> .\node_modules\.pnpm\canvas@2.11.2_encoding@0.1.13\node_modules\canvas
> +-- express@4.19.2 -> .\node_modules\.pnpm\express@4.19.2\node_modules\express
> +-- minecraft-data@3.50.0 -> .\node_modules\.pnpm\minecraft-data@3.50.0\node_modules\minecraft-data
> +-- minecrafthawkeye@1.3.6 -> .\node_modules\.pnpm\minecrafthawkeye@1.3.6\node_modules\minecrafthawkeye
> +-- mineflayer-collectblock-colalab@1.0.0 -> .\node_modules\.pnpm\mineflayer-collectblock-colalab@1.0.0_encoding@0.1.13\node_modules\mineflayer-collectblock-colalab
> +-- mineflayer-pathfinder@2.4.5 -> .\node_modules\.pnpm\mineflayer-pathfinder@2.4.5\node_modules\mineflayer-pathfinder
> +-- mineflayer-pvp@1.3.2 -> .\node_modules\.pnpm\mineflayer-pvp@1.3.2_encoding@0.1.13_prismarine-registry@1.7.0\node_modules\mineflayer-pvp
> +-- mineflayer-tool@1.2.0 -> .\node_modules\.pnpm\mineflayer-tool@1.2.0_encoding@0.1.13\node_modules\mineflayer-tool
> +-- mineflayer@4.14.0 -> .\node_modules\.pnpm\mineflayer@4.14.0_encoding@0.1.13\node_modules\mineflayer
> +-- prismarine-viewer-colalab@1.0.11 -> .\node_modules\.pnpm\prismarine-viewer-colalab@1.0.11_encoding@0.1.13\node_modules\prismarine-viewer-colalab
> `-- vec3@0.1.8 -> .\node_modules\.pnpm\vec3@0.1.8\node_modules\vec3
> ```
> 
> If you found the version is not match. You can check the [package-lock.json](https://github.com/cocacola-lab/MineLand/blob/main/mineland/sim/mineflayer/package-lock.json) under `mineflayer` folder and use `npm ci` to install in correct version.

Thanks for your reply!

I tried to install the same version combination as you, but the problem was not solved

wph@ /home/wph
├── minecraft-data@3.50.0
└── mineflayer@4.14.0

**Comment by YXHXianYu** [comment]
I still think the problem may be caused by inconsistent versions.

Could you provide more information about your node.js environment?

At present, I don't have enough information to determine the cause of the problem. In my experience, this issue is caused by inconsistent versions of Node.js or its dependencies. (If you haven't modified any source code)

Please provide the output of the following commands:
1. npm list
2. node --version
3. npm --version
4. npm config get registry

If possible, please provide the following files:
1. `package-lock.json` in your `mineland/sim/mineflayer`

**Comment by WPH22** [comment]
> I still think the problem may be caused by inconsistent versions.
> 
> Could you provide more information about your node.js environment?
> 
> At present, I don't have enough information to determine the cause of the problem. In my experience, this issue is caused by inconsistent versions of Node.js or its dependencies. (If you haven't modified any source code)
> 
> Please provide the output of the following commands:
> 
> 1. npm list
> 2. node --version
> 3. npm --version
> 4. npm config get registry
> 
> If possible, please provide the following files:
> 
> 1. `package-lock.json` in your `mineland/sim/mineflayer`

thanks! Here are logs and this file.

[package-lock.json](https://github.com/user-attachments/files/17365101/package-lock.json)
![image](https://github.com/user-attachments/assets/e05156a8-25a1-4a3c-95fa-55b2c03a2497)

**Comment by YXHXianYu** [comment]
My npm version is 10.1.0. And your `package-lock.json` doesn't match the MineLand repo.

You can try the following steps to fix:
1. execute `npm install -g npm@10.1.0`. (upgrade npm)
2. remove the whole `mineland/sim/mineflayer` folder. (remove node_modules and the wrong package-lock.json)
3. clone or download a new mineland project and copy the `mineland/sim/mineflayer` folder into the old `mineland/sim` folder. (make sure all files are correct)
4. execute `npm ci` under the new `mineland/sim/mineflayer` folder. (install dependencies with correct package-lock.json)

I hope these help!

**Comment by WPH22** [comment]
> My npm version is 10.1.0. And your `package-lock.json` doesn't match the MineLand repo.
> 
> You can try the following steps to fix:
> 
> 1. execute `npm install -g npm@10.1.0`. (upgrade npm)
> 2. remove the whole `mineland/sim/mineflayer` folder. (remove node_modules and the wrong package-lock.json)
> 3. clone or download a new mineland project and copy the `mineland/sim/mineflayer` folder into the old `mineland/sim` folder. (make sure all files are correct)
> 4. execute `npm ci` under the new `mineland/sim/mineflayer` folder. (install dependencies with correct package-lock.json)
> 
> I hope these help!

thank you very much! It works now!
